### ISSUE TITLE
LinAlgError during training

### ISSUE THREAD

**Issue by MatthewLee11** [ClementPinard/SfmLearner-Pytorch#11]
Hi,

Thanks for the PyTorch version. I met a LinAlgError when I'm trying to train on KITTI. Here's the detailed information.

Traceback (most recent call last):
  File "train.py", line 390, in <module>
    main()
  File "train.py", line 188, in main
    train_loss = train(train_loader, disp_net, pose_exp_net, optimizer, args.epoch_size, logger, train_writer)
  File "train.py", line 236, in train
    for i, (tgt_img, ref_imgs, intrinsics, intrinsics_inv) in enumerate(train_loader):
  File "/home/liyuchen/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "/home/liyuchen/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
numpy.linalg.linalg.LinAlgError: Traceback (most recent call last):
  File "/home/liyuchen/anaconda2/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "./datasets/sequence_folders.py", line 61, in __getitem__
    return tgt_img, ref_imgs, intrinsics, np.linalg.inv(intrinsics)
  File "/home/liyuchen/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 513, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/liyuchen/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 90, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
LinAlgError: Singular matrix

Do you know why?
Thank you.

**Comment by ClementPinard** [comment]
This error is triggered when your intrinsics matrix is not Invertible. Intrinsics matrix usually are in the form of
```
[[fx, 0, cx]
 [0, fy, cy]
 [0,  0,  1]]
```
so it should not happen. How did you preprocess your KITTI dataset ? do you have a sample of `cam.txt` from your dataset ?

**Comment by MatthewLee11** [comment]
@ClementPinard Thank you for your answer. I checked the cam.txt and found the value of intrinsics is 0.000000,0.,0.000000,0.,0.000000,0.000000,0.,0.,1. and I don't know why.  Is it because I use python2.7 instead of python3? I will install PyTorch based on python3 and try again to see if it's the reason. Thank you.

**Comment by MatthewLee11** [comment]
@ClementPinard I solved the problem. It's just because of the version of python. Thank you very much!

**Comment by ClementPinard** [comment]
thanks for your insight ! does it mean that running data preprocessing script with python 2.7 ? I'm curious about what went wrong :)

**Comment by MatthewLee11** [comment]
@ClementPinard I'm so sorry that I didn't log on to GitHub these days. Your guessing is right. I use python 2.7 to run data preprocessing script and met the problem.

**Comment by MatthewLee11** [comment]
@ClementPinard When I used python3.6 to run the scripy, I solved the problem.
