### ISSUE TITLE
error throwing with multi threads in prepare_train_data.py 

### ISSUE THREAD

**Issue by sanweiliti** [ClementPinard/SfmLearner-Pytorch#44]
Hi, 
I tried to tun prepare_train_data.py using the command you provided (num_thread=4), but got the following error message:

> joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/siwei/Desktop/SfmLearner-Pytorch-master/data/prepare_train_data.py", line 33, in dump_example
    dump_dir = args.dump_root/scene_data['rel_path']
AttributeError: 'Namespace' object has no attribute 'dump_root'
"""

> The above exception was the direct cause of the following exception:

> Traceback (most recent call last):
  File "/Users/siwei/Desktop/SfmLearner-Pytorch-master/data/prepare_train_data.py", line 109, in <module>
    main()
  File "/Users/siwei/Desktop/SfmLearner-Pytorch-master/data/prepare_train_data.py", line 86, in main
    Parallel(n_jobs=args.num_threads)(delayed(dump_example)(scene) for scene in tqdm(data_loader.scenes))
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 930, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: 'Namespace' object has no attribute 'dump_root'

Do you have any idea why? The error didn't happen when I used only one thread.

**Comment by sanweiliti** [comment]
Hi, @ClementPinard,
Thanks for the update. Now when I run prepare_train_data.py, it got stuck shortly after the script started running (just stuck and gave no output files), do you know why?

**Comment by ClementPinard** [comment]
Is is still working with only one thread ?

**Comment by sanweiliti** [comment]
No, it also got stuck with only one thread after several iterations.

**Comment by sunnyHelen** [comment]
Yeah. I got the same problem. It just got stuck here.
![image](https://user-images.githubusercontent.com/28101548/52922056-e6eb1d80-3371-11e9-8dc8-7496b4ced617.png)
Do you know how to solve it? @ClementPinard @sanweiliti

**Comment by ClementPinard** [comment]
It's not actually stuck. The progress bar only display how the tasks are dispatched. the bar being at 100% only means that every task is either finished or dispatched. If you wait a little you will see that the program will end.

I am making a coming to use concurrent futures library instead of joblib to use the function [as_completed](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed) and display the real progress of finished tasks.

**Comment by ClementPinard** [comment]
I just uploaded a commit that now uses pebble instead of joblib. That way the colorbar will reflect finished tasks.

**Comment by sunnyHelen** [comment]
Thank you very much. I waited for about 2 hours. Then the program ended.
So I'm running train.py now. But there's an error now.
![image](https://user-images.githubusercontent.com/28101548/52981312-10b84900-3433-11e9-910f-a153ec95be75.png)
I checked the size of depth and intrinsics are all same as you comment in the code.

**Comment by sunnyHelen** [comment]
My version of pytorch is 1.0.0. It seems the batch inverse function can't work. And unfortunately，I can't update the pytorch. I want to ask if there's any way to realize it.

**Comment by ClementPinard** [comment]
Before 1.0.1, the inverse function works only for 2D matrix, so you can just decompose the batch matrix, inverse every matrix and then reassemble everythin with a stack
```python
M = torch.randn(10,3,3)  # batch matrix
invM_list = [m.inverse() for m in M]
invM = torch.stack(invM_list, dim=0)
```

**Comment by sunnyHelen** [comment]
Yeah. Thank you very much for your help~
